[project]
name = "cinturonTopacio"
type = "micropython"

[micropython]
# This must match your board
board = "rp2040-pico"
main = "main.py"

[wokwi]
version = 1
elf = "RPI_PICO-20240602-v1.23.0.uf2"
firmware = "RPI_PICO-20240602-v1.23.0.uf2"
rfc2217ServerPort = 4000